export const ADD_ITENS = 'ADD_ITENS';
export const DEL_ITENS = 'DEL_ITENS';
export const ADD_PRODUCTS_TO_LIST = 'ADD_PRODUCTS_TO_LIST';
export const VISIBILITY_MODAL_PRODUCT = 'VISIBILITY_MODAL_PRODUCT';
export const ALTER_QUANTITY_PRODUCTS = 'ALTER_QUANTITY_PRODUCTS';