export const IS_LOGGED = 'IS_LOGGED';
export const ADD_ITENS = 'ADD_ITENS';
export const DEL_ITENS = 'DEL_ITENS';
export const DEL_ALL_ITENS = 'DEL_ALL_ITENS';
export const ADD_PRODUCTS_TO_LIST = 'ADD_PRODUCTS_TO_LIST';
export const ALTER_QUANTITY_PRODUCTS = 'ALTER_QUANTITY_PRODUCTS';